---
- name: Playbook that runs a Python script
  hosts: localhost
  vars:
    websource: http://api.open-notify.org/astros.json

  tasks:
  - name: Copy script to target hosts and execute it
    script: ~/ans/lab48/scripts/nasaLookup.py
    args:
      executable: /usr/bin/python3
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines

