---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes

  vars:
    delete: false

  tasks:
   - name: make a directory
     file:
       path: ~/output/
       state: directory

   - name: use shell module with wildcarding
     shell: echo $HOME >> ~/output/path.txt

   - name: Debug output
     debug:
             msg: "{{ delete }} |bool"

   - name: delete file
     file:
             path: ~/output/path.txt
             state: absent
     when:  delete|bool
